# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Azure Pipeline Template for deploying models

parameters:
- name: environment
  type: string
- name: serviceConnection
  type: string
- name: resourceGroup
  type: string
- name: amlWorkspace
  type: string
- name: deploymentType
  type: string
- name: webserviceName
  type: string
- name: deleteAfterwards
  type: string
  default: false
- name: artifactName
  type: string
  default: ''


jobs:

- ${{ if eq(parameters.deploymentType, 'aks') }}:
  - job: check_aks
    displayName: 'AKS Check'
    steps:
      - bash: |
          if [ "$(AKS_COMPUTE)" == "" ]; then
            >&2 echo "Error: variable AKS_COMPUTE must be set for AKS deployments"
          fi
        displayName: 'Check AKS_COMPUTE variable'
        failOnStderr: true

- template: utils/deploy-aml-endpoint.template.yml
  parameters:
    environment: $(ENVIRONMENT)
    jobName: deploy_model
    jobDisplayName: 'Deploy Model'
    ${{ if eq(parameters.deploymentType, 'aks') }}:
      dependsOn: check_aks
    serviceConnection: ${{parameters.serviceConnection}}
    resourceGroup: ${{parameters.resourceGroup}}
    amlWorkspace: ${{parameters.amlWorkspace}}
    artifactName: ${{parameters.artifactName}}
    deploymentScript: operation/execution/deploy_model.py
    scriptArguments: |
      --model-name $(AML_MODEL_NAME) \
      --config-path configuration/compute/${{parameters.environment}}-realtimeinference-webservice-${{parameters.deploymentType}}.yml \
      --env-path $(AML_REALTIMEINFERENCE_ENV_PATH) \
      --service-name ${{parameters.webserviceName}} \
      --aks-target-name $(AKS_COMPUTE)

- job: smoke_test
  displayName: 'Test Webservice'
  dependsOn: deploy_model
  steps:
  - template: utils/run-aml-python-code.template.yml
    parameters:
      serviceConnection: ${{parameters.serviceConnection}}
      resourceGroup: ${{parameters.resourceGroup}}
      amlWorkspace: ${{parameters.amlWorkspace}}
      scriptPath: operation/execution/smoke_test_webservice.py
      scriptArguments: --webservice-name ${{parameters.webserviceName}}
      scriptExtraDependencies: pyyaml requests

- ${{ if eq(parameters.deleteAfterwards, 'true') }}:
  - job: delete_webservice
    displayName: 'Delete Webservice'
    dependsOn: smoke_test
    steps:
    # TODO: temporary fixed for bug in az cli 2.30 is corrected
    # Downgrade azure-devops 0.21.0 due to this error: https://github.com/microsoft/dstoolkit-mlops-base/issues/47
    - task: AzureCLI@1
      displayName: 'Downgrade azure-devops 0.21.0'
      inputs:
        azureSubscription: ${{parameters.serviceConnection}}
        scriptLocation: inlineScript
        inlineScript: |
          az extension remove --name azure-devops
          az extension add --name azure-devops --version 0.21.0
    # Downgrade az cli due to this error: https://github.com/microsoft/dstoolkit-mlops-base/issues/47
    - task: Bash@3
      displayName: "Bash: Downgrade AZ CLI to [2.29.2]"
      inputs:
        targetType: "inline"
        workingDirectory: "$(Build.SourcesDirectory)"
        script: |
          sudo add-apt-repository https://packages.microsoft.com/repos/azure-cli
          sudo apt update
          apt-cache policy azure-cli
          sudo apt install -y --allow-downgrades azure-cli=2.29.2-1~bionic

    - task: AzureCLI@1
      name: delete_webservice
      displayName: 'Delete Webservice'
      inputs:
        azureSubscription: ${{parameters.serviceConnection}}
        scriptLocation: inlineScript
        inlineScript: |
          # Install ML extension
          az extension add -n azure-cli-ml
          # Delete webservice
          az ml service delete --name ${{parameters.webserviceName}} \
                               --workspace-name ${{parameters.amlWorkspace}} \
                               --resource-group ${{parameters.resourceGroup}}
        failOnStandardError: true
